<?xml version="1.0" encoding="UTF-8"?>
<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:cab="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        targetNamespace="http://www.univ-grenoble-alpes.fr/l3miage/medical"
        elementFormDefault="qualified">

    <element name="cabinet" type="cab:Cabinet">
        <key name="idInfirmierKey">
            <selector xpath="cab:infirmiers/cab:infirmier"/>
            <field xpath="@id"/>
        </key>
    </element>

    <complexType name="Cabinet">
        <sequence>
            <element name="nom" type="string"/>
            <element name="adresse" type="cab:Adresse"/>
            <element name="infirmiers" type="cab:Infirmiers"/>
            <element name="patients" type="cab:Patients"/>
        </sequence>
    </complexType>

    <complexType name="Adresse">
        <sequence>
            <element name="etage" type="int" minOccurs="0"/>
            <element name="numero" type="int" minOccurs="0"/>
            <element name="rue" type="string"/>
            <element name="codePostal" type="cab:CodePostal"/>
            <element name="ville" type="string"/>
        </sequence>
    </complexType>

    <complexType name="Infirmiers">
        <sequence>
            <element name="infirmier" type="cab:Infirmier"
                     minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Infirmier">
        <sequence>
            <element name="nom" type="cab:NomComplet"/>
            <element name="prenom" type="cab:NomComplet"/>
            <element name="photo" type="cab:PhotoChemin"/>
        </sequence>
        <attribute name="id" type="cab:IdIntervenant" use="required"/>
    </complexType>

    <complexType name="Patients">
        <sequence>
            <element name="patient" type="cab:Patient"
                     minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Patient">
        <sequence>
            <element name="nom" type="cab:NomComplet"/>
            <element name="prenom" type="cab:NomComplet"/>
            <element name="sexe" type="cab:Sexe"/>
            <element name="naissance" type="cab:Naissance"/>
            <element name="numero" type="cab:Numero"/>
            <element name="adresse" type="cab:Adresse"/>
            <element name="visite" type="cab:Visite"/>
        </sequence>
    </complexType>

    <complexType name="Visite">
        <sequence>
            <element name="acte" type="cab:Acte"/>
        </sequence>
        <attribute name="date" type="date"/>
        <attribute name="intervenant" type="cab:IdIntervenant"/>
    </complexType>

    <complexType name="Acte">
        <attribute name="id" type="string"/>
    </complexType>

    <simpleType name="CodePostal">
        <restriction base="string">
            <pattern value="(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}"/>
        </restriction>
    </simpleType>

    <simpleType name="Sexe">
        <restriction base="string">
            <enumeration value="F"/>
            <enumeration value="M"/>
        </restriction>
    </simpleType>

    <simpleType name="Naissance">
        <restriction base="date">
            <minInclusive value="1900-01-01"/>
        </restriction>
    </simpleType>

    <!-- NIR simplifié : 15 chiffres -->
    <simpleType name="Numero">
        <restriction base="string">
            <pattern value="[0-9]{15}"/>
        </restriction>
    </simpleType>

    <simpleType name="NomComplet">
        <restriction base="string">
            <pattern value="[A-Z]?[a-zéèàêâùïüë]+"/>
        </restriction>
    </simpleType>

    <simpleType name="IdIntervenant">
        <restriction base="string">
            <pattern value="\d{3}"/>
        </restriction>
    </simpleType>

    <simpleType name="PhotoChemin">
        <restriction base="string">
            <pattern value=".+\.(png|jpg)"/>
        </restriction>
    </simpleType>

</schema>
