<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="src\data\html\" />
    </ItemGroup>

    <ItemGroup>
      <None Update="src\data\xml\actes.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\xml\cabinet.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\xsd\cabinet.xsd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\xsd\patient.xsd">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\xslt\infirmier.xsl">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\js\buttonScript.js">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\css\style.css">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="src\data\xml\cabinet_modif.xml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
